publishDir = "docs"
baseurl = "https://blog.wataridori.co.jp"
languageCode = "ja"
defaultContentLanguage = "ja"
title = "WATARIDORI BLOG"
theme = "peak"
paginate = 10
canonifyurls = true
googleAnalytics = "UA-98609730-1"

[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  archive = "archives"

[author]
  name = "wataridori inc."
  bio = "未知の体験とワクワクを。"
  # job = "Your job title"
  # location = "Tokyo, Japan"
  # Your Gravatar email. Overwrite `author.picture` everywhere in the blog
  # gravatarEmail = "thibaud.lepretre@gmail.com"
  # Your profile picture
  # Overwritten by your gravatar image if `author.gravatarEmail` is filled
  picture = "https://cdn.rawgit.com/wtrdr/blog/gh-pages/img/logo.jpg"
  # Your Twitter username without the @. E.g : thibaudlepretre
  # twitter = "thibaudlepretre"
  # Your google plus profile id. E.g : +ThibaudLepretre or 114625208755123718311
  # googlePlus = "+ThibaudLepretre"

# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "tags"
  name = "Tags"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-tags\"></i>"
  url = "/tags"
[[menu.main]]
  weight = 3
  identifier = "archives"
  name = "Archives"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-archive\"></i>"
  url = "/archives"
[[menu.main]]
  weight = 4
  identifier = "about"
  name = "About"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-question\"></i>"
  url = "/page/about-us"
[[menu.links]]
  weight = 1
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-github\"></i>"
  url = "https://github.com/wtrdr"
[[menu.links]]
  weight = 2
  identifier = "rss"
  name = "RSS"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-rss\"></i>"
  url = "/index.xml"

[params]
  dateFormat = "2006/01/02"
  keywords = ["ワタリドリ", "ブログ", "wataridori inc."]
  clearReading = true
  hierarchicalCategories = false

  description = "株）ワタリドリのブログ"
  sidebarBehavior = 1
  coverImage = "https://cdn.rawgit.com/wtrdr/blog/gh-pages/img/top.jpg"

  imageGallery = true
  thumbnailImage = true
  thumbnailImagePosition = "top"
  autoThumbnailImage = true

  # fbAdminIds = 
  # fbAppId = 

  # Your favicon path, default is "/favicon.png"
  # favicon = "/favicon.png"

  syntaxHighlighter = "highlight.js"

  [params.sidebar.profile]
    url = "/"

  [params.header.rightLink]
    class = "facebook-link"
    icon = "facebook-official"
    url = "https://www.facebook.com/wataridori.co.jp"

  [[params.sharingOptions]]
    name = "Facebook"
    icon = "fa-facebook-official"
    url = "https://www.facebook.com/sharer/sharer.php?u=%s"

  [[params.sharingOptions]]
    name = "Twitter"
    icon = "fa-twitter"
    url = "https://twitter.com/intent/tweet?text=%s"

  [[params.customCSS]]
    href = "css/custom.css"

[blackfriday]
  extensions = ["hardLineBreak"]
